# Generated by Django 4.0.2 on 2022-02-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='maximum_attende',
            new_name='maximum_attendee',
        ),
    ]
